### ISSUE TITLE
Windows filesystem errors

### ISSUE THREAD

**Issue by anomaliagames** [KTheMan/Mariner-Autoinstaller#1]
Hi,

During your upload or whatever you've managed to insert some Windows line endings. Great script though!

Shows this error:
> `./mariner.sh: line 2: $'\r': command not found
> ./mariner.sh: line 4: $'\r': command not found
> ./mariner.sh: line 6: $'\r': command not found
> ./mariner.sh: line 39: syntax error near unexpected token `$'in\r''
> '/mariner.sh: line 39: `        case $input in`

Hotfix for anyone else:

Download DOS2Unix
`sudo apt-get install dos2unix`

Run on the file
`os2unix mariner.sh`

You can now continue with the rest of the install :)

**Comment by KTheMan** [comment]
I've gone ahead and hopefully fixed this; sound off and reopen if you're still seeing issues though

**Comment by proffrink** [comment]
This is still happening I'm afraid.

**Comment by proffrink** [comment]
Anyone trying to fix this, note that there's a typo in the OP. It should read
`dos2unix mariner.sh`
