### ISSUE TITLE
No service found

### ISSUE THREAD

**Issue by anomaliagames** [KTheMan/Mariner-Autoinstaller#2]
When I run `sudo systemctl status mariner3d` I get `Unit mariner3d.service could not be found.`

I'm running Raspbian light and didn't run an update command - is this something I should be doing first for dependencies?

**Comment by anomaliagames** [comment]
I am rerunning the installer now after some update and upgrade commands.

**Comment by KTheMan** [comment]
Huh that is definitely odd; the script should execute updates and upgrades for you, at the start of the second run of the script.

`    info "Updating repositories and upgrade software; this could take a long time"`
`    sudo apt-get -qq update >/dev/null && sudo apt-get -qq -y upgrade >/dev/null`

And then it would install mariner at the end of that run, starting the service.

Just to double check:
You ran the script, rebooted, and ran the script a second time?

**Comment by proffrink** [comment]
Was on a different account but this was me.

Indeed, after the first reboot it simply continued. I'd probably say this was working as intended. Can probably remove that 'good first issue' tag :D
