### ISSUE TITLE
Change hostname?

### ISSUE THREAD

**Issue by proffrink** [KTheMan/Mariner-Autoinstaller#3]
A change that was made in the latest commit is making it impossible to enter a new hostname before it's parsed

> Change hostname? [Y/n] y
./mariner.sh: line 76: read: `Enter a new hostname (Default 'raspberrypi'): ': not a valid identifier
[info] You can now access this Pi from .local
sudo: unable to resolve host raspberrypi: Name or service not known
[info] rebooting..
sudo: unable to resolve host raspberrypi: Name or service not known
Connection to raspberrypi.local closed by remote host.
Connection to raspberrypi.local closed.

I'll skip this bit for now :)

**Comment by KTheMan** [comment]
I think I've corrected it, but I haven't yet tested it. It's in the develop branch along with use of the new repo to install, if you would like to give it a whirl

**Comment by proffrink** [comment]
Confirm fixed. Sorry for not seeing this sooner.

Again to emphasise: Really useful script - thank you so much.
