### ISSUE TITLE
Use PPA repo

### ISSUE THREAD

**Issue by luizribeiro** [KTheMan/Mariner-Autoinstaller#4]
Hey, thanks for the script :)

Would you be able to update the script to use the newly setup PPA repo? (see luizribeiro/mariner#231)

Now, instead of downloading the `.deb` from the GitHub release pages, you can enable my PPA repo:

```bash
$ curl -sL gpg.l9o.dev | sudo apt-key add -
$ echo "deb https://ppa.l9o.dev/raspbian ./" | sudo tee /etc/apt/sources.list.d/l9o.list
$ sudo apt update
```

And simply install mariner with:

```bash
sudo apt install mariner3d
```

The main advantage is that updates to mariner will be installed automatically through `sudo apt upgrade`, just like every other installed package.

**Comment by KTheMan** [comment]
Perfect! I'll get on it asap
