### ISSUE TITLE
Mariner Not Running After Install

### ISSUE THREAD

**Issue by Rhastlyn** [KTheMan/Mariner-Autoinstaller#6]
Hi --  thanks for putting this together, I tried the manual install instructions on the Mariner3d Documentation and your script and I'm getting the same error:

Here's the output of `sudo systemctl status mariner3d`

● mariner3d.service - mariner3d Printer Controller
     Loaded: loaded (/lib/systemd/system/mariner3d.service; enabled; vendor preset: enab>
     Active: failed (Result: signal) since Sat 2022-07-30 23:54:53 EDT; 2min 26s ago
    Process: 259 ExecStart=/usr/bin/mariner (code=killed, signal=ABRT)
   Main PID: 259 (code=killed, signal=ABRT)
        CPU: 133ms

Jul 30 23:54:51 photonmonopi systemd[1]: Started mariner3d Printer Controller.
Jul 30 23:54:52 photonmonopi mariner[259]: Could not find platform independent libraries>
Jul 30 23:54:52 photonmonopi mariner[259]: Could not find platform dependent libraries <>
Jul 30 23:54:52 photonmonopi mariner[259]: Consider setting $PYTHONHOME to <prefix>[:<ex>
Jul 30 23:54:53 photonmonopi mariner[259]: Fatal Python error: initfsencoding: Unable to>
Jul 30 23:54:53 photonmonopi mariner[259]: ModuleNotFoundError: No module named 'encodin>
Jul 30 23:54:53 photonmonopi mariner[259]: Current thread 0xb6fbaa00 (most recent call f>
Jul 30 23:54:53 photonmonopi systemd[1]: mariner3d.service: Main process exited, code=ki>
Jul 30 23:54:53 photonmonopi systemd[1]: mariner3d.service: Failed with result 'signal'.

**Comment by daniel-tickell** [comment]
+1 have the same issue here trying to debug why it wont start

**Comment by daniel-tickell** [comment]
I followed the instructions here
https://github.com/luizribeiro/mariner/issues/481#issuecomment-968325624

and was able to get it to run. This is not an issue with the install script but mariner3d is the problem

**Comment by KTheMan** [comment]
Sorry, I don't check this particularly often. Thanks for helping each other!

@daniel-tickell is right that this is a Mariner issue; if you still have issues consider opening a ticket on [luizribeiro/mariner](https://github.com/luizribeiro/mariner/issues)
